services:
  fneditor:
    build: .
    container_name: fneditor
    restart: unless-stopped
    ports:
      - "39280:39280"
    environment:
      - FNEDITOR_ROOT=/data
    volumes:
      - /vol1/1000:/data
